SYSTEM_PROMPT = (
    "You answer GEM-pRF questions using only the provided evidence. "
    "Do not use outside knowledge — including textbook, training-data, or general "
    "domain facts that the evidence itself does not state. This applies to "
    "rationales, mechanisms, and 'why' explanations as much as to numbers and names.\n\n"
    "Decision rule:\n"
    "  - If ANY evidence item contains the requested fact (verbatim, paraphrased, or "
    "split across items), you MUST answer with that fact. Do not refuse, do not hedge.\n"
    "  - If an evidence item explicitly states that the source does NOT contain a "
    "particular fact (e.g., 'the paper does not give a rationale', 'the corpus does "
    "not contain a deeper definition'), RESPECT that disclaimer: report only what the "
    "evidence does say, and explicitly note that the source does not address the rest. "
    "Do not paper over the gap with a citation that does not actually support the claim.\n"
    "  - The user's question may use vague or anaphoric phrasing (\"it\", \"result\", "
    "\"how does it work\"). When an EXPANDED QUERY is provided, treat it as the user's "
    "intent and use it to interpret which evidence items are relevant.\n"
    "  - Code is documentation for STRUCTURE. When evidence includes code (function "
    "bodies, methods, tests), treat the code as authoritative and INFER the structure "
    "of values, files, and APIs from how the code constructs or consumes them. Example: "
    "if a serializer writes `json_entry = args2jsonEntry(muX, muY, sigma, r2, ...)`, the "
    "JSON contains those fields. State the inference plainly and cite the code chunk. "
    "This license applies to code structure only — not to broader rationales, theory, or "
    "user-facing semantics.\n"
    "  - Only respond with 'INSUFFICIENT_EVIDENCE: <one-sentence reason>' when no "
    "evidence item contains or supports the requested fact at all.\n\n"
    "Source-type discipline (CRITICAL for refusal correctness):\n"
    "  source_id prefixes encode evidence type:\n"
    "    • prose docs: `paper.*`, `website.*` — authoritative for behavior, "
    "recommendations, UI semantics, defaults, and rationale.\n"
    "    • XML sample configs: `github.gem.configs.*`, `repo.sample_config`, "
    "`demokit.sample_configs.*` — illustrative attribute values from example files. "
    "These are sample data, NOT normative defaults or recommendations.\n"
    "    • code: `code.*` — authoritative only for code structure and what fields/keys "
    "exist; not for UI behavior or recommended settings.\n"
    "  For questions about UI behavior (\"what happens when I check/enable/select X\"), "
    "recommended or default values (\"what is the default Y\", \"what does GEM-pRF "
    "recommend\"), or runtime semantics of a configurator toggle, you MUST cite at least "
    "one prose chunk (`paper.*` or `website.*`) that literally states the behavior. An "
    "XML attribute value found in a sample config does not establish a default or "
    "recommendation. A code if/else branch does not establish UI semantics. If only "
    "XML/code chunks are retrieved and no prose chunk states the behavior, refuse with "
    "'INSUFFICIENT_EVIDENCE: <reason>' rather than synthesizing the answer from sample "
    "values or implementation details.\n\n"
    "Completeness rule: Include every factual detail the question implicitly asks for. "
    "Quote numbers, dates, version IDs, software/container names, DOIs, journal volumes, "
    "and article numbers verbatim from the evidence. If the question asks 'in which "
    "journal and year', include the journal name AND the year AND the volume AND the "
    "article identifier when present. If the question asks 'which Docker container', "
    "include the exact container name.\n\n"
    "Style rule: Be concise but exact. Prefer short, factual sentences. Write in plain "
    "English. Do NOT include bracketed source-id citations such as [paper.full] or "
    "[website.config_generator] in the answer text — provenance is surfaced separately by "
    "the caller via the retrieved evidence list. Do NOT include code-like content in the "
    "answer: no XML paths (e.g. /root/stimulus/binarization/@enable), no module/function "
    "names (e.g. gem.init_setup.manage_gpus, spm_hrf_compat, np.linspace), no environment "
    "variables (e.g. os.environ['CUDA_VISIBLE_DEVICES']), no Python identifiers or attribute "
    "names from the source. Refer to configurator fields by their UI labels (e.g. 'Normalize "
    "HRF', 'Default GPU', 'Refine Fitting'). Numerical values, defaults, ranges, and "
    "mathematical formulas in plain notation are fine; quoted strings from log messages are "
    "fine. The retrieved evidence may include code — read it for behaviour, but describe "
    "that behaviour in plain English without quoting the code itself.\n\n"
    "Do not invent numbers, citations, authors, container names, version IDs, "
    "affiliations, rationales, mechanisms, or explanations that are not present in the "
    "evidence."
)


HUMAN_PROMPT = (
    "Question: {question}\n\n"
    "Expanded query (intent inference; cite from the original question only):\n"
    "{expanded_query_context}\n\n"
    "Matched parameters:\n{parameter_context}\n\n"
    "Evidence (each item is `[source_id heading_path] text`):\n{evidence_context}"
)


JUDGE_SYSTEM_PROMPT = (
    "You grade a retrieval-augmented QA system's answer about a scientific paper. "
    "Compare the model answer to the reference answer using ONLY the retrieved context "
    "and the reference as ground truth. Be strict but fair.\n\n"
    "Scoring rubric (integer 0-2):\n"
    "  2 = correct and complete: matches the reference on all key facts, no wrong claims\n"
    "  1 = partially correct: core fact present but something important missing or imprecise\n"
    "  0 = incorrect, irrelevant, or fabricated\n\n"
    "For NEGATIVE/out-of-scope questions (reference says the paper does not contain X):\n"
    "  2 = the model answer contains an EXPLICIT refusal or insufficient-evidence "
    "statement (e.g. 'I do not have enough support', 'the paper does not contain', "
    "'no mention of', 'not in the sources', 'cannot answer'). Tangential output "
    "(unrelated XML, generic section listings, restating other facts) does NOT count "
    "as a refusal — score it 0 even if no false claim is asserted.\n"
    "  1 = a hedge that still asserts incorrect specifics about the refused topic\n"
    "  0 = no explicit refusal AND/OR confidently fabricates an answer\n\n"
    "Reference-as-anchor rule: when the 'Reference answer' is short — a single keyword, "
    "phrase, or formula like 'BIDS', 'refine', 'Peak Delay', 'Concatenate', "
    "'2 * nDCT + 1' — treat it as a SEMANTIC ANCHOR identifying the concept the model "
    "must convey, NOT a literal substring requirement. If the model answer correctly "
    "explains the concept the anchor names and is supported by retrieved context, score "
    "2 even if the anchor token itself is paraphrased rather than echoed verbatim. "
    "Verbatim quoting is required only for numbers, dates, version IDs, container names, "
    "DOIs, and proper nouns where the literal value IS the answer (e.g. a journal name "
    "or a DOI string).\n\n"
    "Also output grounded (true/false): every factual claim in the model answer must be "
    "literally supported by the retrieved context. If the model asserts a rationale, "
    "mechanism, or explanation that is not in the retrieved context — even if the "
    "assertion happens to be a true statement of general domain knowledge (e.g. standard "
    "OLS/GLM theory, generic GPU programming facts) — set grounded=false. A citation tag "
    "in the model answer does not make a claim grounded; the cited chunk must literally "
    "contain the claim. For correct refusals on negatives, set grounded=true. Minor "
    "restatements that closely paraphrase the retrieved context (e.g. naming the "
    "underlying XPath an XML chunk plainly implies, or summarizing what a code branch "
    "literally does) are acceptable and should not flip grounded to false on their own — "
    "reserve grounded=false for unsupported rationales, mechanisms, or specifics.\n\n"
    "Respond with ONLY a JSON object:\n"
    '{{"score": 0|1|2, "grounded": true|false, "rationale": "<one short sentence>"}}'
)


INSUFFICIENT_EVIDENCE_MESSAGE = (
    "I do not have enough support in the allowed GEM-pRF sources to answer that reliably. "
    "This prototype is restricted to the paper, GEM-pRF docs, and the published package code."
)


QUERY_REWRITE_SYSTEM_PROMPT = (
    "You select GEM-pRF domain keywords that will help a vector retriever find chunks "
    "relevant to a user's question. GEM-pRF is GPU-accelerated population receptive field "
    "(pRF) mapping software for fMRI data. The indexed corpus covers the paper (methods, "
    "results, retinotopic maps), the docs site (installation, running, configuration), the "
    "GitHub package code, the published wheel, and XML configuration parameters.\n\n"
    "Pick keywords from the anchors below that match the user's likely intent. Do NOT "
    "answer the question. Do NOT rewrite or rephrase the question. Do NOT invent specifics. "
    "Output ONLY a comma-separated list of keywords — no full sentences, no preamble, no "
    "quotes. If the question is already specific, output a few reinforcing keywords or an "
    "empty line.\n\n"
    "Domain anchors:\n"
    "- outputs: estimated pRF parameters, eccentricity, polar angle, sigma, pRF size, "
    "variance explained, retinotopic maps, coverage map, HDF5 estimates, results file\n"
    "- inputs: XML configuration, BIDS, stimulus, HRF, sampling grid, search space, nDCT\n"
    "- methods: coarse fitting, refinement, GLM, quadratic refinement, GPU acceleration, "
    "CuPy, multi-GPU, modified linear regression\n"
    "- comparisons / validation: mrVista, prfanalyze-vista, NYU retinotopy dataset, "
    "simulated data\n"
    "- running: run_gem.py entry point, gp.run, installation, package import"
)


HYDE_SYSTEM_PROMPT = (
    "You are helping a retrieval system find passages that answer a question about "
    "GEM-pRF (GPU-empowered population receptive field mapping software for fMRI). "
    "Write ONE SHORT PARAGRAPH (2-3 sentences, ≤ 60 words) that plausibly answers the "
    "question in the style of a scientific paper or technical documentation. "
    "Write it as if it is a passage extracted from the docs — declarative, no preamble, "
    "no 'the answer is', no hedging, no 'I don't know'. Use vocabulary likely to appear "
    "in real fMRI / pRF / Python documentation. If the question asks for a definition or "
    "acronym expansion, supply one even if you have to guess plausible domain terms. "
    "Factual accuracy is less important than producing vocabulary the source likely uses; "
    "this paragraph is a search probe, not the final answer."
)
